services:
  builder:
    image: ${COMPOSE_PROJECT_NAME}-builder
    build:
      context: .
      dockerfile: Dockerfile
  api:
    build:
      context: .
      dockerfile: ./projects/api-project/Dockerfile
      args:
        - BUILDER_IMAGE=${COMPOSE_PROJECT_NAME}-builder
    depends_on:
      - builder

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./src/api/Dockerfile
  #     args:
  #       - DEPS_IMAGE=deps
  #   ports:
  #     - 8000:8000
