[project]
name = "shared"
version = "0.1.0"
description = "Default template for PDM package"
authors = []
dependencies = []
requires-python = ">=3.10"
license = { text = "_" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
